print ("Timothy John U. Timtiman")
print ("Bangbangalon, Boac, Marinduque")
print ("February 19, 2001") 
print ("Marinduque State College, BSIT 2E")
print ("Playing Online Competitive Games")
print ("Basketball")
print ("Learning codes")
print ("Playing with my pet cat")
print ("Reading")
